-- Use SQL insert statements to add any
-- starting/dummy data to your database tables
-- insert into "recipes" ("idMeal", "strMeal", "strInstructions", "strMealThumb", "ingredients", "measurements", "strYoutube", "userId", "sharedBy", "seenShared")
-- EXAMPLE:

--  insert into "todos"
--    ("task", "isCompleted")
--    values
--      ('Learn to code', false),
--      ('Build projects', false),
--      ('Get a job', false);
